### ISSUE TITLE
Genome-wide significance of summary stats SNPs

### ISSUE THREAD

**Issue by Prakrithi-P** [LeonSong1995/gsMap#8]
Hi,
  Thank you for the amazing tool. I have just tested it on some samples and looks great. However, I was wondering why all SNPs from summary stats, irrespective of whether they pass the genome-wide p-value are used? How do we interpret the results and would this not affect our findings? The results don't look as good when I use only SNPs from summary stats that have p<5x10-8. Any suggestions regarding this? 

Thanks and regards,
Prakrithi

**Comment by LeonSong1995** [comment]
Hi Prakrithi,


Thank you for your interest in our work. SNPs that do not pass the significance threshold (i.e., 5e-8) are not necessarily uninformative, as their individual effects may be too small to meet the stringent significance criteria in GWAS. gsMap performs partitioned heritability enrichment analysis, and our previous work has demonstrated that SNPs with minor effects (that do not pass the threshold) contribute significantly to the heritability of complex traits. For a more detailed explanation, please refer to the following link to our previous work. https://www.nature.com/articles/ng.608



Best regards,
Liyang

**Comment by Prakrithi-P** [comment]
Thank you for the prompt response. I tried the tool with all SNPs and genome-wide SNPs from a summary stats and different genes and cell types show up as top hits. So was wondering what would be the best thing to do. I'll have a look at the paper you sent and decide what works best and get back to you if I need help.

Thanks again!
Prakrithi

**Comment by LeonSong1995** [comment]
No problem :smile:. Please feel free to raise an issue if you encounter any difficulties during gsMap analysis.
