### ISSUE TITLE
Output Interpretation

### ISSUE THREAD

**Issue by Prakrithi-P** [LeonSong1995/gsMap#9]
Hi again, 
 I just needed help understanding the outputs of Gene_Diagnostic_Info.csv
What exactly does PCC represent? 
Gene,Annotation,Median_GSS,PCC

Thanks and regards,
Prakrithi

**Comment by Prakrithi-P** [comment]
I think I got the answer to the above question upon going through diagnosis.py.

Also, I would like to generate a GSS plot for a gene that is not in the top 50 list but way down the line. When I use --selected_genes 'geneX', I get an error (screenshot attached).  Is it because the gene I want to plot is not in the top 50? Let's say it's the 1000th gene and I specify top_corr_genes 1000, I still get the same error. Could you please suggest what I can do in this case? And just to be sure the whole gsMap plot is based on all genes and not just the top 50 right? 

Thanks and regards,
Prakrithi

![image](https://github.com/user-attachments/assets/4aca2738-4f2d-4373-addc-c5d4b08ee771)

**Comment by LeonSong1995** [comment]
Hi Prakrithi,

1) This warning indicates that there are no GWAS signals for your specified gene. You may need to check whether this gene is included in your ST dataset and consider providing a larger gene list for plotting.

2) Yes, gsMap results are based on all SNPs (not just those mapped to the top 50 genes). We displayed the top 50 genes for model diagnostics. Changing the --`top_corr_genes` parameter in the `generate report` subcommand will not affect the gsMap mapping results.

Best,
Leon

**Comment by Prakrithi-P** [comment]
Hi Leon, 
  Thanks for the response! The genes I am trying to plot are in the ST data and also have a PCC of 0.4-0.5 and I still get the error. What does it mean if there is no GWAS signals but the PCC is still >0.4?

Thanks,
Prakrithi

**Comment by LeonSong1995** [comment]
Hi Prakrithi,
 
There are two possible reasons: 
1) Your gene may not be listed in the GTF file used in gsMap. Please check whether the GTF file (i.e., `gencode.v39lift37.annotation.gtf`, if you are using our provided GTF) contains the gene of interest.

2) SNPs located in the cis-window (±50 KB of a gene's transcribed region) of a gene are assigned to that gene. In cases where genes overlap, gsMap assigns SNPs to the closest gene by default. For example, if gene A and gene B overlap, SNPs located within the cis-windows of both genes will be assigned to gene A. Consequently, you may not observe GWAS signals for gene B if you attempt to plot it.  
                  <img width="412" alt="SnptoGene" src="https://github.com/user-attachments/assets/7ddd8c42-7ac1-4334-8047-2acf2d97d637" />

Best, 
Leon

**Comment by Prakrithi-P** [comment]
Makes sense. Thank you. It was probably Point #2 in my case. If you don't mind could you explain how PCC is calculated even with no GWAS signal ? - Because, I thought the logP that correlates with GSS is from the GWAS SNPs.

Also, even if the gene is not enriched for GWAS, the GSS should have been independent of that right - since it's the very first step. I couldn't locate the code used to make the GSS plot,. Couls you please help with that too?

**Comment by LeonSong1995** [comment]
Yes, GSS is independent of GWAS. The process in gsMap is as follows: for each individual cell

compute GSS using the ST data -> assign GSS to SNPs to compute the stratified LD score -> perform LD score regression analysis. 

After this process, you obtain logP values for each cell. The PCC is then calculated as the correlation between GSS (dim: cell-by-1) and logP (dim: cell-by-1). Therefore, even if a gene is not assigned to any SNPs, you can still compute the PCC for that gene.

The code for GSS plotting is located in 
`diagnosis.py` at line 160:`generate_GSS_distribution`.

**Comment by Prakrithi-P** [comment]
Hi again Leon,
    I tried running gsMAP with custom gtf annotations. The new features are in the Gene_Diagnostic_info file (PCC is calculated) but somehow not incorporated in the generate_ldscore step and not found in the feather files and hence not in the manhattan plot. Could you hep with what step I should be looking into? I think it is something to do with the mk_score file (.feather) generating step.

Thanks,
Prakrithi
